version: "3.7"
services:
  otel:
    image: amazon/aws-otel-collector:latest
    command: --config /config/collector-config.yml
    volumes:
      - .:/config
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION=us-west-2
    ports:
      - '4317:4317'

  app:
    image: ${APP_IMAGE}
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - INSTANCE_ID
      - LISTEN_ADDRESS
      - AWS_REGION=us-west-2
      - OTEL_RESOURCE_ATTRIBUTES=service.name=aws-otel-integ-test
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4317
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - '8080:8080'    

  validator:
    image: public.ecr.aws/u0d6r4y4/aws-otel-test-validator:alpha
    command: ${VALIDATOR_COMMAND}
    depends_on:
      - otel
      - app
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION=us-west-2      
     
